### ISSUE TITLE
user-can-view-carousel

### ISSUE THREAD

**Issue by HuynhCynthia** [HuynhCynthia/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see carousel of products. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Carousel will automatically cycle through various products. User will be able to navigate back-and-forth between carousel slides. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![user can create an entry desktop](https://user-images.githubusercontent.com/115051720/221962269-4711f858-310e-4c95-a0dc-211c5345f92e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Complete the HTML form using the appropriate responsive layout classes.
  - [x] Write CSS desktop first.
  - [x] Adjust styling to fluidly adapt to mobile devices.
- [x] In carousel section add arrow icons to allow user to navigate through carousel
- [x] Create array with chosen product Id's to feature
- [x] Create a function that populates tiles and images in carousel
    - [x] Obtain product array  with API request
    - [x] Add event listener that will create DOM tree for carousel
- [x] Create a function that will automatically transition next group of images to another group of product images
- [x] Create a function that will allow user to click arrows to transition to next group of product images
- **Clean Up**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
