### ISSUE TITLE
user-can-view-list-of-product-images

### ISSUE THREAD

**Issue by HuynhCynthia** [HuynhCynthia/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see images of list of products.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When user clicks on category name page will switch to page view where list of products from specific category are shown. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature
![Screen Shot 2023-03-03 at 9 26 18 AM](https://user-images.githubusercontent.com/115051720/222787402-7a8ae6fc-25b1-4ea5-bc12-e35e181ae7da.png)
![Screen Shot 2023-03-03 at 9 26 25 AM](https://user-images.githubusercontent.com/115051720/222787405-d2c968d1-29b0-4af0-a573-6e688c6f69d1.png)

- [x] Define function that will store value of selected category type in local storage
- [x] Make request to api to retrieve a list of products from selected category
- [x] Define a function that will generate specific banner image of certain category
- [x] Define another function that will generate DOM elements of product images
  - [x] Establish for loop that will iterate through the length category products
  - [x] Use the image property and assign to src attribute
  - [x] Ensure each product images is in span element
  - [x] Give classname it image element
  - [x] Create data type attribute to identify unique product
  - [x] Create node list for span elements and add click event listener to each span
      - [x] Each click should store data type id in local storage
  - [x] Add title and price using properties of product list 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
